// import Css
// print(getType(Animation.self) ? "extension Key.Animation: HasValueOfNone {}" : "///extension Key.Animation: HasValueOfNone {}")
// print(getType(AnimationDelay.self) ? "extension Key.AnimationDelay: HasValueOfNone {}" : "///extension Key.AnimationDelay: HasValueOfNone {}")
// print(getType(AnimationDirection.self) ? "extension Key.AnimationDirection: HasValueOfNone {}" : "///extension Key.AnimationDirection: HasValueOfNone {}")
// print(getType(AnimationDuration.self) ? "extension Key.AnimationDuration: HasValueOfNone {}" : "///extension Key.AnimationDuration: HasValueOfNone {}")
// print(getType(AnimationFillMode.self) ? "extension Key.AnimationFillMode: HasValueOfNone {}" : "///extension Key.AnimationFillMode: HasValueOfNone {}")
// print(getType(AnimationIterationCount.self) ? "extension Key.AnimationIterationCount: HasValueOfNone {}" : "///extension Key.AnimationIterationCount: HasValueOfNone {}")
// print(getType(AnimationName.self) ? "extension Key.AnimationName: HasValueOfNone {}" : "///extension Key.AnimationName: HasValueOfNone {}")
// print(getType(AnimationPlayState.self) ? "extension Key.AnimationPlayState: HasValueOfNone {}" : "///extension Key.AnimationPlayState: HasValueOfNone {}")
// print(getType(AnimationTimingFunction.self) ? "extension Key.AnimationTimingFunction: HasValueOfNone {}" : "///extension Key.AnimationTimingFunction: HasValueOfNone {}")
// print()
// print(getType(Background.self) ? "extension Key.Background: HasValueOfNone {}" : "///extension Key.Background: HasValueOfNone {}")
// print(getType(BackgroundAttachment.self) ? "extension Key.BackgroundAttachment: HasValueOfNone {}" : "///extension Key.BackgroundAttachment: HasValueOfNone {}")
// print(getType(BackgroundBlendMode.self) ? "extension Key.BackgroundBlendMode: HasValueOfNone {}" : "///extension Key.BackgroundBlendMode: HasValueOfNone {}")
// print(getType(BackgroundClip.self) ? "extension Key.BackgroundClip: HasValueOfNone {}" : "///extension Key.BackgroundClip: HasValueOfNone {}")
// print(getType(BackgroundColor.self) ? "extension Key.BackgroundColor: HasValueOfNone {}" : "///extension Key.BackgroundColor: HasValueOfNone {}")
// print(getType(BackgroundImage.self) ? "extension Key.BackgroundImage: HasValueOfNone {}" : "///extension Key.BackgroundImage: HasValueOfNone {}")
// print(getType(BackgroundOrigin.self) ? "extension Key.BackgroundOrigin: HasValueOfNone {}" : "///extension Key.BackgroundOrigin: HasValueOfNone {}")
// print(getType(BackgroundPosition.self) ? "extension Key.BackgroundPosition: HasValueOfNone {}" : "///extension Key.BackgroundPosition: HasValueOfNone {}")
// print(getType(BackgroundRepeat.self) ? "extension Key.BackgroundRepeat: HasValueOfNone {}" : "///extension Key.BackgroundRepeat: HasValueOfNone {}")
// print(getType(BackgroundSize.self) ? "extension Key.BackgroundSize: HasValueOfNone {}" : "///extension Key.BackgroundSize: HasValueOfNone {}")
// print()
// print(getType(Border.self) ? "extension Key.Border: HasValueOfNone {}" : "///extension Key.Border: HasValueOfNone {}")
// print(getType(BorderBottom.self) ? "extension Key.BorderBottom: HasValueOfNone {}" : "///extension Key.BorderBottom: HasValueOfNone {}")
// print(getType(BorderBottomColor.self) ? "extension Key.BorderBottomColor: HasValueOfNone {}" : "///extension Key.BorderBottomColor: HasValueOfNone {}")
// print(getType(BorderBottomLeftRadius.self) ? "extension Key.BorderBottomLeftRadius: HasValueOfNone {}" : "///extension Key.BorderBottomLeftRadius: HasValueOfNone {}")
// print(getType(BorderBottomRightRadius.self) ? "extension Key.BorderBottomRightRadius: HasValueOfNone {}" : "///extension Key.BorderBottomRightRadius: HasValueOfNone {}")
// print(getType(BorderBottomStyle.self) ? "extension Key.BorderBottomStyle: HasValueOfNone {}" : "///extension Key.BorderBottomStyle: HasValueOfNone {}")
// print(getType(BorderBottomWidth.self) ? "extension Key.BorderBottomWidth: HasValueOfNone {}" : "///extension Key.BorderBottomWidth: HasValueOfNone {}")
// print(getType(BorderCollapse.self) ? "extension Key.BorderCollapse: HasValueOfNone {}" : "///extension Key.BorderCollapse: HasValueOfNone {}")
// print(getType(BorderColor.self) ? "extension Key.BorderColor: HasValueOfNone {}" : "///extension Key.BorderColor: HasValueOfNone {}")
// print(getType(BorderImage.self) ? "extension Key.BorderImage: HasValueOfNone {}" : "///extension Key.BorderImage: HasValueOfNone {}")
// print(getType(BorderImageOutset.self) ? "extension Key.BorderImageOutset: HasValueOfNone {}" : "///extension Key.BorderImageOutset: HasValueOfNone {}")
// print(getType(BorderImageRepeat.self) ? "extension Key.BorderImageRepeat: HasValueOfNone {}" : "///extension Key.BorderImageRepeat: HasValueOfNone {}")
// print(getType(BorderImageSlice.self) ? "extension Key.BorderImageSlice: HasValueOfNone {}" : "///extension Key.BorderImageSlice: HasValueOfNone {}")
// print(getType(BorderImageSource.self) ? "extension Key.BorderImageSource: HasValueOfNone {}" : "///extension Key.BorderImageSource: HasValueOfNone {}")
// print(getType(BorderImageWidth.self) ? "extension Key.BorderImageWidth: HasValueOfNone {}" : "///extension Key.BorderImageWidth: HasValueOfNone {}")
// print(getType(BorderLeft.self) ? "extension Key.BorderLeft: HasValueOfNone {}" : "///extension Key.BorderLeft: HasValueOfNone {}")
// print(getType(BorderLeftColor.self) ? "extension Key.BorderLeftColor: HasValueOfNone {}" : "///extension Key.BorderLeftColor: HasValueOfNone {}")
// print(getType(BorderLeftStyle.self) ? "extension Key.BorderLeftStyle: HasValueOfNone {}" : "///extension Key.BorderLeftStyle: HasValueOfNone {}")
// print(getType(BorderLeftWidth.self) ? "extension Key.BorderLeftWidth: HasValueOfNone {}" : "///extension Key.BorderLeftWidth: HasValueOfNone {}")
// print(getType(BorderRadius.self) ? "extension Key.BorderRadius: HasValueOfNone {}" : "///extension Key.BorderRadius: HasValueOfNone {}")
// print(getType(BorderRight.self) ? "extension Key.BorderRight: HasValueOfNone {}" : "///extension Key.BorderRight: HasValueOfNone {}")
// print(getType(BorderRightColor.self) ? "extension Key.BorderRightColor: HasValueOfNone {}" : "///extension Key.BorderRightColor: HasValueOfNone {}")
// print(getType(BorderRightStyle.self) ? "extension Key.BorderRightStyle: HasValueOfNone {}" : "///extension Key.BorderRightStyle: HasValueOfNone {}")
// print(getType(BorderRightWidth.self) ? "extension Key.BorderRightWidth: HasValueOfNone {}" : "///extension Key.BorderRightWidth: HasValueOfNone {}")
// print(getType(BorderSpacing.self) ? "extension Key.BorderSpacing: HasValueOfNone {}" : "///extension Key.BorderSpacing: HasValueOfNone {}")
// print(getType(BorderStyle.self) ? "extension Key.BorderStyle: HasValueOfNone {}" : "///extension Key.BorderStyle: HasValueOfNone {}")
// print(getType(BorderTop.self) ? "extension Key.BorderTop: HasValueOfNone {}" : "///extension Key.BorderTop: HasValueOfNone {}")
// print(getType(BorderTopColor.self) ? "extension Key.BorderTopColor: HasValueOfNone {}" : "///extension Key.BorderTopColor: HasValueOfNone {}")
// print(getType(BorderTopLeftRadius.self) ? "extension Key.BorderTopLeftRadius: HasValueOfNone {}" : "///extension Key.BorderTopLeftRadius: HasValueOfNone {}")
// print(getType(BorderTopRightRadius.self) ? "extension Key.BorderTopRightRadius: HasValueOfNone {}" : "///extension Key.BorderTopRightRadius: HasValueOfNone {}")
// print(getType(BorderTopStyle.self) ? "extension Key.BorderTopStyle: HasValueOfNone {}" : "///extension Key.BorderTopStyle: HasValueOfNone {}")
// print(getType(BorderTopWidth.self) ? "extension Key.BorderTopWidth: HasValueOfNone {}" : "///extension Key.BorderTopWidth: HasValueOfNone {}")
// print(getType(BorderWidth.self) ? "extension Key.BorderWidth: HasValueOfNone {}" : "///extension Key.BorderWidth: HasValueOfNone {}")
// print()
// print(getType(TextColor.self) ? "extension Key.Color: HasValueOfNone {}" : "///extension Key.Color: HasValueOfNone {}")
// print(getType(Opacity.self) ? "extension Key.Opacity: HasValueOfNone {}" : "///extension Key.Opacity: HasValueOfNone {}")
// print()
// print(getType(Height.self) ? "extension Key.Height: HasValueOfNone {}" : "///extension Key.Height: HasValueOfNone {}")
// print(getType(MinHeight.self) ? "extension Key.MinHeight: HasValueOfNone {}" : "///extension Key.MinHeight: HasValueOfNone {}")
// print(getType(MaxHeight.self) ? "extension Key.MaxHeight: HasValueOfNone {}" : "///extension Key.MaxHeight: HasValueOfNone {}")
// print(getType(Width.self) ? "extension Key.Width: HasValueOfNone {}" : "///extension Key.Width: HasValueOfNone {}")
// print(getType(MinWidth.self) ? "extension Key.MinWidth: HasValueOfNone {}" : "///extension Key.MinWidth: HasValueOfNone {}")
// print(getType(MaxWidth.self) ? "extension Key.MaxWidth: HasValueOfNone {}" : "///extension Key.MaxWidth: HasValueOfNone {}")
// print()
// print(getType(AlignContent.self) ? "extension Key.AlignContent: HasValueOfNone {}" : "///extension Key.AlignContent: HasValueOfNone {}")
// print(getType(AlignItems.self) ? "extension Key.AlignItems: HasValueOfNone {}" : "///extension Key.AlignItems: HasValueOfNone {}")
// print(getType(AlignSelf.self) ? "extension Key.AlignSelf: HasValueOfNone {}" : "///extension Key.AlignSelf: HasValueOfNone {}")
// print(getType(Flex.self) ? "extension Key.Flex: HasValueOfNone {}" : "///extension Key.Flex: HasValueOfNone {}")
// print(getType(FlexBasis.self) ? "extension Key.FlexBasis: HasValueOfNone {}" : "///extension Key.FlexBasis: HasValueOfNone {}")
// print(getType(FlexDirection.self) ? "extension Key.FlexDirection: HasValueOfNone {}" : "///extension Key.FlexDirection: HasValueOfNone {}")
// print(getType(FlexFlow.self) ? "extension Key.FlexFlow: HasValueOfNone {}" : "///extension Key.FlexFlow: HasValueOfNone {}")
// print(getType(FlexGrow.self) ? "extension Key.FlexGrow: HasValueOfNone {}" : "///extension Key.FlexGrow: HasValueOfNone {}")
// print(getType(FlexShrink.self) ? "extension Key.FlexShrink: HasValueOfNone {}" : "///extension Key.FlexShrink: HasValueOfNone {}")
// print(getType(FlexWrap.self) ? "extension Key.FlexWrap: HasValueOfNone {}" : "///extension Key.FlexWrap: HasValueOfNone {}")
// print(getType(JustifyContent.self) ? "extension Key.JustifyContent: HasValueOfNone {}" : "///extension Key.JustifyContent: HasValueOfNone {}")
// print(getType(Order.self) ? "extension Key.Order: HasValueOfNone {}" : "///extension Key.Order: HasValueOfNone {}")
// print()
// print(getType(Font.self) ? "extension Key.Font: HasValueOfNone {}" : "///extension Key.Font: HasValueOfNone {}")
// print(getType(FontFamily.self) ? "extension Key.FontFamily: HasValueOfNone {}" : "///extension Key.FontFamily: HasValueOfNone {}")
// print(getType(FontFeatureSettings.self) ? "extension Key.FontFeatureSettings: HasValueOfNone {}" : "///extension Key.FontFeatureSettings: HasValueOfNone {}")
// print(getType(FontKerning.self) ? "extension Key.FontKerning: HasValueOfNone {}" : "///extension Key.FontKerning: HasValueOfNone {}")
// print(getType(FontSize.self) ? "extension Key.FontSize: HasValueOfNone {}" : "///extension Key.FontSize: HasValueOfNone {}")
// print(getType(FontSizeAdjust.self) ? "extension Key.FontSizeAdjust: HasValueOfNone {}" : "///extension Key.FontSizeAdjust: HasValueOfNone {}")
// print(getType(FontStretch.self) ? "extension Key.FontStretch: HasValueOfNone {}" : "///extension Key.FontStretch: HasValueOfNone {}")
// print(getType(FontStyle.self) ? "extension Key.FontStyle: HasValueOfNone {}" : "///extension Key.FontStyle: HasValueOfNone {}")
// print(getType(FontVariant.self) ? "extension Key.FontVariant: HasValueOfNone {}" : "///extension Key.FontVariant: HasValueOfNone {}")
// print(getType(FontVariantCaps.self) ? "extension Key.FontVariantCaps: HasValueOfNone {}" : "///extension Key.FontVariantCaps: HasValueOfNone {}")
// print(getType(FontWeight.self) ? "extension Key.FontWeight: HasValueOfNone {}" : "///extension Key.FontWeight: HasValueOfNone {}")
// print()
// print(getType(Content.self) ? "extension Key.Content: HasValueOfNone {}" : "///extension Key.Content: HasValueOfNone {}")
// print(getType(Quotes.self) ? "extension Key.Quotes: HasValueOfNone {}" : "///extension Key.Quotes: HasValueOfNone {}")
// print(getType(CounterReset.self) ? "extension Key.CounterReset: HasValueOfNone {}" : "///extension Key.CounterReset: HasValueOfNone {}")
// print(getType(CounterIncrement.self) ? "extension Key.CounterIncrement: HasValueOfNone {}" : "///extension Key.CounterIncrement: HasValueOfNone {}")
// print()
// print(getType(ListStyle.self) ? "extension Key.ListStyle: HasValueOfNone {}" : "///extension Key.ListStyle: HasValueOfNone {}")
// print(getType(ListStyleType.self) ? "extension Key.ListStyleType: HasValueOfNone {}" : "///extension Key.ListStyleType: HasValueOfNone {}")
// print(getType(ListStylePosition.self) ? "extension Key.ListStylePosition: HasValueOfNone {}" : "///extension Key.ListStylePosition: HasValueOfNone {}")
// print(getType(ListStyleImage.self) ? "extension Key.ListStyleImage: HasValueOfNone {}" : "///extension Key.ListStyleImage: HasValueOfNone {}")
// print()
// print(getType(Margin.self) ? "extension Key.Margin: HasValueOfNone {}" : "///extension Key.Margin: HasValueOfNone {}")
// print(getType(MarginBottom.self) ? "extension Key.MarginBottom: HasValueOfNone {}" : "///extension Key.MarginBottom: HasValueOfNone {}")
// print(getType(MarginLeft.self) ? "extension Key.MarginLeft: HasValueOfNone {}" : "///extension Key.MarginLeft: HasValueOfNone {}")
// print(getType(MarginRight.self) ? "extension Key.MarginRight: HasValueOfNone {}" : "///extension Key.MarginRight: HasValueOfNone {}")
// print(getType(MarginTop.self) ? "extension Key.MarginTop: HasValueOfNone {}" : "///extension Key.MarginTop: HasValueOfNone {}")
// print()
// print(getType(ColumnCount.self) ? "extension Key.ColumnCount: HasValueOfNone {}" : "///extension Key.ColumnCount: HasValueOfNone {}")
// print(getType(ColumnFill.self) ? "extension Key.ColumnFill: HasValueOfNone {}" : "///extension Key.ColumnFill: HasValueOfNone {}")
// print(getType(ColumnGap.self) ? "extension Key.ColumnGap: HasValueOfNone {}" : "///extension Key.ColumnGap: HasValueOfNone {}")
// print(getType(ColumnRule.self) ? "extension Key.ColumnRule: HasValueOfNone {}" : "///extension Key.ColumnRule: HasValueOfNone {}")
// print(getType(ColumnRuleColor.self) ? "extension Key.ColumnRuleColor: HasValueOfNone {}" : "///extension Key.ColumnRuleColor: HasValueOfNone {}")
// print(getType(ColumnRuleStyle.self) ? "extension Key.ColumnRuleStyle: HasValueOfNone {}" : "///extension Key.ColumnRuleStyle: HasValueOfNone {}")
// print(getType(ColumnRuleWidth.self) ? "extension Key.ColumnRuleWidth: HasValueOfNone {}" : "///extension Key.ColumnRuleWidth: HasValueOfNone {}")
// print(getType(ColumnSpan.self) ? "extension Key.ColumnSpan: HasValueOfNone {}" : "///extension Key.ColumnSpan: HasValueOfNone {}")
// print(getType(ColumnWidth.self) ? "extension Key.ColumnWidth: HasValueOfNone {}" : "///extension Key.ColumnWidth: HasValueOfNone {}")
// print(getType(Columns.self) ? "extension Key.Columns: HasValueOfNone {}" : "///extension Key.Columns: HasValueOfNone {}")
// print()
// print(getType(Outline.self) ? "extension Key.Outline: HasValueOfNone {}" : "///extension Key.Outline: HasValueOfNone {}")
// print(getType(OutlineColor.self) ? "extension Key.OutlineColor: HasValueOfNone {}" : "///extension Key.OutlineColor: HasValueOfNone {}")
// print(getType(OutlineOffset.self) ? "extension Key.OutlineOffset: HasValueOfNone {}" : "///extension Key.OutlineOffset: HasValueOfNone {}")
// print(getType(OutlineStyle.self) ? "extension Key.OutlineStyle: HasValueOfNone {}" : "///extension Key.OutlineStyle: HasValueOfNone {}")
// print(getType(OutlineWidth.self) ? "extension Key.OutlineWidth: HasValueOfNone {}" : "///extension Key.OutlineWidth: HasValueOfNone {}")
// print()
// print(getType(Padding.self) ? "extension Key.Padding: HasValueOfNone {}" : "///extension Key.Padding: HasValueOfNone {}")
// print(getType(PaddingBottom.self) ? "extension Key.PaddingBottom: HasValueOfNone {}" : "///extension Key.PaddingBottom: HasValueOfNone {}")
// print(getType(PaddingLeft.self) ? "extension Key.PaddingLeft: HasValueOfNone {}" : "///extension Key.PaddingLeft: HasValueOfNone {}")
// print(getType(PaddingRight.self) ? "extension Key.PaddingRight: HasValueOfNone {}" : "///extension Key.PaddingRight: HasValueOfNone {}")
// print(getType(PaddingTop.self) ? "extension Key.PaddingTop: HasValueOfNone {}" : "///extension Key.PaddingTop: HasValueOfNone {}")
// print()
// print(getType(BreakAfter.self) ? "extension Key.BreakAfter: HasValueOfNone {}" : "///extension Key.BreakAfter: HasValueOfNone {}")
// print(getType(BreakBefore.self) ? "extension Key.BreakBefore: HasValueOfNone {}" : "///extension Key.BreakBefore: HasValueOfNone {}")
// print(getType(BreakInside.self) ? "extension Key.BreakInside: HasValueOfNone {}" : "///extension Key.BreakInside: HasValueOfNone {}")
// print()
// print(getType(TextAlign.self) ? "extension Key.TextAlign: HasValueOfNone {}" : "///extension Key.TextAlign: HasValueOfNone {}")
// print(getType(TextAlignLast.self) ? "extension Key.TextAlignLast: HasValueOfNone {}" : "///extension Key.TextAlignLast: HasValueOfNone {}")
// print(getType(TextDecoration.self) ? "extension Key.TextDecoration: HasValueOfNone {}" : "///extension Key.TextDecoration: HasValueOfNone {}")
// print(getType(TextDecorationColor.self) ? "extension Key.TextDecorationColor: HasValueOfNone {}" : "///extension Key.TextDecorationColor: HasValueOfNone {}")
// print(getType(TextDecorationLine.self) ? "extension Key.TextDecorationLine: HasValueOfNone {}" : "///extension Key.TextDecorationLine: HasValueOfNone {}")
// print(getType(TextDecorationStyle.self) ? "extension Key.TextDecorationStyle: HasValueOfNone {}" : "///extension Key.TextDecorationStyle: HasValueOfNone {}")
// print(getType(TextIndent.self) ? "extension Key.TextIndent: HasValueOfNone {}" : "///extension Key.TextIndent: HasValueOfNone {}")
// print(getType(TextJustify.self) ? "extension Key.TextJustify: HasValueOfNone {}" : "///extension Key.TextJustify: HasValueOfNone {}")
// print(getType(TextOverflow.self) ? "extension Key.TextOverflow: HasValueOfNone {}" : "///extension Key.TextOverflow: HasValueOfNone {}")
// print(getType(TextShadow.self) ? "extension Key.TextShadow: HasValueOfNone {}" : "///extension Key.TextShadow: HasValueOfNone {}")
// print(getType(TextTransform.self) ? "extension Key.TextTransform: HasValueOfNone {}" : "///extension Key.TextTransform: HasValueOfNone {}")
// print(getType(LineHeight.self) ? "extension Key.LineHeight: HasValueOfNone {}" : "///extension Key.LineHeight: HasValueOfNone {}")
// print(getType(LetterSpacing.self) ? "extension Key.LetterSpacing: HasValueOfNone {}" : "///extension Key.LetterSpacing: HasValueOfNone {}")
// print()
// print(getType(BackfaceVisibility.self) ? "extension Key.BackfaceVisibility: HasValueOfNone {}" : "///extension Key.BackfaceVisibility: HasValueOfNone {}")
// print(getType(Transform.self) ? "extension Key.Transform: HasValueOfNone {}" : "///extension Key.Transform: HasValueOfNone {}")
// print(getType(TransformOrigin.self) ? "extension Key.TransformOrigin: HasValueOfNone {}" : "///extension Key.TransformOrigin: HasValueOfNone {}")
// print(getType(TransformStyle.self) ? "extension Key.TransformStyle: HasValueOfNone {}" : "///extension Key.TransformStyle: HasValueOfNone {}")
// print()
// print(getType(Transition.self) ? "extension Key.Transition: HasValueOfNone {}" : "///extension Key.Transition: HasValueOfNone {}")
// print(getType(TransitionDelay.self) ? "extension Key.TransitionDelay: HasValueOfNone {}" : "///extension Key.TransitionDelay: HasValueOfNone {}")
// print(getType(TransitionDuration.self) ? "extension Key.TransitionDuration: HasValueOfNone {}" : "///extension Key.TransitionDuration: HasValueOfNone {}")
// print(getType(TransitionProperty.self) ? "extension Key.TransitionProperty: HasValueOfNone {}" : "///extension Key.TransitionProperty: HasValueOfNone {}")
// print(getType(TransitionTimingFunction.self) ? "extension Key.TransitionTimingFunction: HasValueOfNone {}" : "///extension Key.TransitionTimingFunction: HasValueOfNone {}")
// print()
// print(getType(Display.self) ? "extension Key.Display: HasValueOfNone {}" : "///extension Key.Display: HasValueOfNone {}")
// print(getType(Position.self) ? "extension Key.Position: HasValueOfNone {}" : "///extension Key.Position: HasValueOfNone {}")
// print(getType(Top.self) ? "extension Key.Top: HasValueOfNone {}" : "///extension Key.Top: HasValueOfNone {}")
// print(getType(Right.self) ? "extension Key.Right: HasValueOfNone {}" : "///extension Key.Right: HasValueOfNone {}")
// print(getType(Bottom.self) ? "extension Key.Bottom: HasValueOfNone {}" : "///extension Key.Bottom: HasValueOfNone {}")
// print(getType(Left.self) ? "extension Key.Left: HasValueOfNone {}" : "///extension Key.Left: HasValueOfNone {}")
// print(getType(BoxFloat.self) ? "extension Key.Float: HasValueOfNone {}" : "///extension Key.Float: HasValueOfNone {}")
// print(getType(Clear.self) ? "extension Key.Clear: HasValueOfNone {}" : "///extension Key.Clear: HasValueOfNone {}")
// print(getType(ZIndex.self) ? "extension Key.ZIndex: HasValueOfNone {}" : "///extension Key.ZIndex: HasValueOfNone {}")
// print(getType(Overflow.self) ? "extension Key.Overflow: HasValueOfNone {}" : "///extension Key.Overflow: HasValueOfNone {}")
// print(getType(OverflowX.self) ? "extension Key.OverflowX: HasValueOfNone {}" : "///extension Key.OverflowX: HasValueOfNone {}")
// print(getType(OverflowY.self) ? "extension Key.OverflowY: HasValueOfNone {}" : "///extension Key.OverflowY: HasValueOfNone {}")
// print(getType(ClipPath.self) ? "extension Key.ClipPath: HasValueOfNone {}" : "///extension Key.ClipPath: HasValueOfNone {}")
// print(getType(Visibility.self) ? "extension Key.Visibility: HasValueOfNone {}" : "///extension Key.Visibility: HasValueOfNone {}")
// print(getType(BoxDecorationBreak.self) ? "extension Key.BoxDecorationBreak: HasValueOfNone {}" : "///extension Key.BoxDecorationBreak: HasValueOfNone {}")
// print(getType(BoxShadow.self) ? "extension Key.BoxShadow: HasValueOfNone {}" : "///extension Key.BoxShadow: HasValueOfNone {}")
// print(getType(BoxSizing.self) ? "extension Key.BoxSizing: HasValueOfNone {}" : "///extension Key.BoxSizing: HasValueOfNone {}")
// print(getType(CaretColor.self) ? "extension Key.CaretColor: HasValueOfNone {}" : "///extension Key.CaretColor: HasValueOfNone {}")
// print(getType(Cursor.self) ? "extension Key.Cursor: HasValueOfNone {}" : "///extension Key.Cursor: HasValueOfNone {}")


// func getType<T: None>(_: T.Type) -> Bool {
//   return true
// }

// @_disfavoredOverload
// func getType<T>(_: T.Type) -> Bool {
//   return false
// }