public protocol ChildOfAny {}

extension Text:        ChildOfAny {}
extension Raw:         ChildOfAny {}
extension Comment:     ChildOfAny {}
//extension Element:     ChildOfAny where Kind: ChildOfAny {}

extension Array:       ChildOfAny where Element: ChildOfAny {}
extension Either:      ChildOfAny where Left: ChildOfAny, Right: ChildOfAny {}
extension Empty:       ChildOfAny {}
extension Optional:    ChildOfAny where Wrapped: ChildOfAny {}

extension A: ChildOfAny {}
extension Abbr: ChildOfAny {}
extension Address: ChildOfAny {}
extension Article: ChildOfAny {}
extension Aside: ChildOfAny {}
extension Audio: ChildOfAny {}
extension B: ChildOfAny {}
extension Bdi: ChildOfAny {}
extension Bdo: ChildOfAny {}
extension Blockquote: ChildOfAny {}
extension Br: ChildOfAny {}
extension Button: ChildOfAny {}
extension Canvas: ChildOfAny {}
extension Cite: ChildOfAny {}
extension Code: ChildOfAny {}
extension Del: ChildOfAny {}
extension Details: ChildOfAny {}
extension Dfn: ChildOfAny {}
extension Div: ChildOfAny {}
extension Dl: ChildOfAny {}
extension Em: ChildOfAny {}
extension Fieldset: ChildOfAny {}
extension Figure: ChildOfAny {}
extension Footer: ChildOfAny {}
extension Form: ChildOfAny {}
extension H1: ChildOfAny {}
extension H2: ChildOfAny {}
extension H3: ChildOfAny {}
extension H4: ChildOfAny {}
extension H5: ChildOfAny {}
extension H6: ChildOfAny {}
extension Header: ChildOfAny {}
extension Hr: ChildOfAny {}
extension I: ChildOfAny {}
extension Iframe: ChildOfAny {}
extension Img: ChildOfAny {}
extension Input: ChildOfAny {}
extension Ins: ChildOfAny {}
extension Kbd: ChildOfAny {}
extension Label: ChildOfAny {}
extension Main: ChildOfAny {}
extension Map: ChildOfAny {}
extension Mark: ChildOfAny {}
extension Meter: ChildOfAny {}
extension Nav: ChildOfAny {}
extension Noscript: ChildOfAny {}
extension Object: ChildOfAny {}
extension Ol: ChildOfAny {}
extension Optgroup: ChildOfAny {}
extension Output: ChildOfAny {}
extension P: ChildOfAny {}
extension Picture: ChildOfAny {}
extension Pre: ChildOfAny {}
extension Progress: ChildOfAny {}
extension Q: ChildOfAny {}
extension S: ChildOfAny {}
extension Samp: ChildOfAny {}
extension Script: ChildOfAny {}
extension Section: ChildOfAny {}
extension Select: ChildOfAny {}
extension Small: ChildOfAny {}
extension Span: ChildOfAny {}
extension Strong: ChildOfAny {}
extension Sub: ChildOfAny {}
extension Sup: ChildOfAny {}
extension Svg: ChildOfAny {}
extension Table: ChildOfAny {}
extension Template: ChildOfAny {}
extension Textarea: ChildOfAny {}
extension Time: ChildOfAny {}
extension U: ChildOfAny {}
extension Ul: ChildOfAny {}
extension Var: ChildOfAny {}
extension Video: ChildOfAny {}
